site:
  title: histlog Documentation
  url: https://example.invalid/histlog/
  start_page: histlog::index.adoc

content:
  sources:
    - url: .
      start_path: docs

output:
  dir: ./dist/antora

ui:
  bundle:
    url: https://gitlab.com/antora/default-ui/-/jobs/artifacts/main/raw/build/ui-bundle.zip?job=build
    snapshot: true
